kind: Service
apiVersion: v1
metadata:
  name: meteor
  labels:
    app: meteor
spec:
  type: NodePort
  selector:
    app: meteor
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: meteor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meteor
  template:
    metadata:
      labels:
        app: meteor
        version: v1
    spec:
      containers:
      - name: meteor
        image: ghcr.io/whichlicense/platform-microservices/meteor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ghpat
